### PR TITLE
Update on the recent nixpkgs refactor

### LINKED ISSUE #120: Native load path not injected with latest nixpkgs changes
Recently this was merged: https://github.com/NixOS/nixpkgs/pull/235859

I think this affects the wrapper:
https://github.com/emacs-twist/twist.nix/blob/82cb3be3b1e6c9a88729a5e2951f99d3e55ad9c9/pkgs/emacs/wrapper.nix#L21

Probably a less breaking change from this change would be to still have this attribute propagated on the Emacs derivation as well not only in the input.

### PR DESCRIPTION
**Pull request by akirak**
Fixes #120.

### CODE REVIEW

**Comment by terlar** [comment]
I think you need to change this as well, right?
https://github.com/emacs-twist/twist.nix/blob/master/pkgs/emacs/build/default.nix#L20

**Comment by akirak** [comment]
@terlar You are right, thanks.

**Comment by terlar** [comment]
Used your PR as input and without my manual fix and it solved the issue, thank you.

**Comment by akirak** [comment]
Thank you for the feedback!

**Pull request merged**
